openapi: 3.0.0
info:
  title: Log API
  description: Log API for Channel logs
  version: v1
servers:
  - url: https://container-gateway-https-route-gbipaas-caapigateway-test.paast.fw.garanti.com.tr/channels/technical/logs/v1/log
    description: Development Container Gateway URL on the Openshift
paths:
  /channels/technical/logs/v1/log:
    post:
      summary: Create a log record for Channel
      description: Create a log record for Channel log
      parameters:
        - in: header
          name: channel
          schema:
            type: string
          required: true
        - in: header
          name: Authorization
          schema:
            type: string 
        - in: header
          name: ip
          schema:
            type: string
          required: true
        - in: header
          name: dialect
          schema:
            type: string
          required: true
        - in: header
          name: Content-Type
          schema:
            type: string
          required: true
        - in: header
          name: companyId
          schema:
            type: string 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                timeStamp:
                  type: string
                userAgent:
                  type: string
                deviceInfo:
                  type: string
                originURL:
                  type: string 
                operationComponent:
                  type: string
                logMask:
                  type: string
                hostNodeIp:
                  type: string
                userName:
                  type: string
                auditDescription:
                  type: string
                auditDetail:
                  type: string                 
      responses:
        '200':
          description: Return operation result.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/result'
components:
  schemas:
    result:
       properties:
        returnCode:
          type: integer
        reasonCode:
          type: integer
        messageText:
          type: string 
        '500':
          description: Internal Server Error
        default:
          description: Unexpected error